### ISSUE TITLE
feature/agregar-logging

### ISSUE THREAD

**Issue by EqualNoches** [SBR-2/SBR-backend#12]
El backend del proyecto actualmente no tiene implementado un sistema de `logging` adecuado, lo cual dificulta el rastreo de errores, eventos importantes y problemas de rendimiento. Contar con un sistema de logging centralizado permitirá monitorear el comportamiento de la aplicación de manera más efectiva y detectar errores de manera más rápida.

- [ ] Logging funciona correctamente

**Comment by shinso-raven** [comment]
Serilog implementando con el pull request Bpm-inspeccion

implementacion
`Log.Information(string mensaje);`
